import { NextAuthProvider } from '@/shared/providers'

export const metadata = {
    manifest: '/manifest.json',
    themeColor: '#ffffff',
    title: 'Fapp',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
            <body>
                <NextAuthProvider>{children}</NextAuthProvider>
            </body>
        </html>
    )
}
